name: infoq-daily-163
on:
  schedule:
    - cron: "0 15 * * *"   # 夏令时对应 LA 08:00
    - cron: "0 16 * * *"   # 冬令时对应 LA 08:00
  workflow_dispatch: {}     # 允许手动触发
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - env:
          GATE_PACIFIC_8AM: "true"   # 临时想立刻测试可改成 "false"
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: python daily_infoq_leads.py
